### ISSUE TITLE
Difference between BrainSpace and original Margulies PNAS 2016 methods

### ISSUE THREAD

**Issue by sophiatinh** [MICA-MNI/BrainSpace#54] opened 2021-08-30 07:44 UTC
Hi,

I have a curious question regarding the difference in the embedding calculations of Brain Space and the one used in the 2016 PNAS paper by Margulies et al. I have tried feeding the same z matrix into both set of codes. Both used the same methods and parameters for thresholding, affinity matrix calculation and embedding (alpha, diffusion time). However there are some variations in the gradient unit (-0.1->0.1 vs -10->15) and especially the amount of variance explained by the top 2 gradients (11% and 10.6% for Brainspace vs 30.9% and 19.2% for Margulies PNAS 2016). The correlation of the 2 gradients between the methods are relatively high (>0.9 for both) but I'm curious on why the component variance as calculated by the ratio of lambda differs so much. Any explaination would be much appreciated!

Have a good day!  
Sophia

**Comment by ReinderVosDeWael** [comment] 2021-08-30 14:35
Hi Sophia,

Different packages will generally have some subtle differences due to implementation details. I'm not sure which BrainSpace version you're using, but if it's MATLAB then even just the differences between numpy/scipy and MATLAB's inbuilt functions could make quite a difference. 

The only design difference between BrainSpace and the Margulies PNAS methods that I'm aware of is that we sparsify the matrix before the kernel computation whereas they, if I recall correctly, sparsify after the kernel computation. As such I'd assume that if you set your sparsity threshold to 0 (i.e. no thresholding) then the difference would be smaller.

**Comment by sophiatinh** [comment] 2021-08-31 09:27
Thank you so much for your prompt reply. I has indeed been using MATLAB Brainspace version 0.1.1. 
I checked the code and it seemed like they also carried out sparsification before the kernel computation. However,  I discovered that they used the cosine distance as kernel and using that I obtained the exact same embedding values with correlation of +/-1 across all 10 components between the methods. However the amount of variance explained by the components still remains very different (11% and 10.8% for Brainspace vs 30.9% and 19.2% for Margulies PNAS 2016). This puzzled me as the components extracted has exactly the same values.
Taking your advice regarding the difference between matlab and python into account, I reran the analysis with Brainspace using Python and it only gave 10 components as reflected by the lambda values instead of 19 using the matlab package. If I again take the eigenvalues of the first 2 components and divide it by the sum of eigenvalues for all 10 components reported, now it's 34. 7% vs 21.4%, which is indeed closer to what was reported previously by Marguiles group. But it's still curious how the eigenvalues change so much across platform? And also any idea why only 10 components got extracted using the python pipeline?

**Comment by ReinderVosDeWael** [comment] 2021-09-01 14:08
I'm not too sure why the eigenvalues diverge this much, unfortunately, as I'm not familiar with the minute details of the Margulies implementation. Regarding the number of components. There's a parameter `n_components` which determines the number of components returned (by default 10). There's a small discrepancy between our Python and MATLAB implementations here; MATLAB will return all computed eigenvalues irrespective of the number of requested components whereas Python only returns the eigenvalues corresponding to the number of requested components (see the [API](https://brainspace.readthedocs.io/en/latest/generated/brainspace.gradient.gradient.GradientMaps.html#brainspace.gradient.gradient.GradientMaps)). If you want 19 components in Python simply set `n_components` to 19.

**Comment by ReinderVosDeWael** [comment] 2021-09-01 14:09
Regarding the divergence between our MATLAB/Python implementation: can you send me the code you used to run this?

**Comment by sophiatinh** [comment] 2021-09-01 15:27
These are the codes used for the matlab and python implementation. I have included the lamba output for the top 2 gradients as well.

Matlab:
ave=table2array(readtable([maindir '/gradient_analysis-master_Marguiles/zmat_ave_45.csv']));
%using cosine distance
gref_cos = GradientMaps('kernel','cs');
gref_cos = gref_cos.fit(tanh(ave));
>> gref_cos.lambda{1}
ans =
    0.8755
    0.8132....

Python:
# Load data and Fisher's z-to-r transform
from numpy import genfromtxt
conn_matrix =  np.tanh(genfromtxt('zmat_ave_45.csv', delimiter=','))
from brainspace.gradient import GradientMaps

# Ask for 19 gradients 
gm = GradientMaps(kernel='cosine', approach='dm', random_state=0,n_components=19)
gm.fit(np.tanh(conn_matrix))

gm.lambdas_
array([6.98549798, 4.31413149,...

**Comment by ReinderVosDeWael** [comment] 2021-09-01 16:29
Would you mind mkaign the zmat_ave_45.csv file available? That could help me with reproducing this.

**Comment by sophiatinh** [comment] 2021-09-01 17:38
[zmat_ave_45.csv](https://github.com/MICA-MNI/BrainSpace/files/7093257/zmat_ave_45.csv)
Hope it helps!

**Comment by ReinderVosDeWael** [comment] 2021-09-01 21:21
I've found the cause of the divergence between MATLAB and Python. Long story short: there is an error in the scaling of the MATLAB eigenvalues. Note that the order of the eigenvalues as well as the eigenvectors (i.e. gradients) were unaffected.

I'll try to push out a fix for this ASAP, but in the short term you can do either of the following:

- Use the Python implementation for the magnitude of eigenvalues.
- Open the file `diffusion_mapping.m` and replace the first line
```matlab
function [embedding,lambda] = diffusion_mapping(data, n_components, alpha, diffusion_time, random_state)
``` 
with 
```matlab
function [embedding, scaled_eigval] = diffusion_mapping(data, n_components, alpha, diffusion_time, random_state)
``` 

Thanks for your help.

**Comment by sophiatinh** [comment] 2021-09-07 06:24
That explained it. Thanks for your help!

**Comment by ReinderVosDeWael** [comment] 2021-09-07 18:02
A fix for this issue has been pushed to master.

**Closed as completed by ReinderVosDeWael** 2021-09-07 18:02 UTC
Labels: bug, MATLAB
